[dependencies.libprocon]
git = 'https://github.com/magurotuna/libprocon.git'

[dependencies]
num-bigint = "0.2.6"

[package]
authors = ['Yusuke Tanaka <wing0920@gmail.com>']
edition = '2018'
name = 'abc152'
version = '0.1.0'
[profile.release]
lto = true
panic = 'abort'
