[package]
name = "agc043"
version = "0.1.0"
authors = ["Yusuke Tanaka <wing0920@gmail.com>"]
edition = "2018"

[dependencies]
libprocon = { git = "https://github.com/magurotuna/libprocon.git" }

[profile.release]
lto = true
panic = 'abort'
